# Wrapper for running Boost's bootstrap.bat on Visual Studio 2025 / VS 18
# (VFX-CY2025 experimental). Invoked via `cmake -P`.
#
# Required -D arguments:
#   SRC_DIR      — Boost source directory (BUILD_IN_SOURCE)
#   TOOLSET      — Boost toolset name (e.g. msvc-14.3)
#   PYTHON_BIN   — absolute path to python.exe
#   CL_EXE       — absolute path to cl.exe for the default MSVC toolset
#   VCVARSALL    — absolute path to vcvarsall.bat
#   VS_COMNTOOLS — absolute path to VS Common7/Tools (no trailing backslash)
#
# Why this exists: Boost.Build's msvc.jam 14.3 parent-path logic cannot locate
# vcvarsall.bat for the VS 2025 / VS 18 install layout, so we supply the
# vcvarsall.bat path explicitly via <setup> after bootstrap.bat has built b2.

IF(NOT SRC_DIR OR NOT CL_EXE OR NOT VCVARSALL OR NOT VS_COMNTOOLS)
  MESSAGE(FATAL_ERROR "boost_bootstrap_vs2025.cmake: SRC_DIR, CL_EXE, VCVARSALL, VS_COMNTOOLS are required")
ENDIF()

# Pre-inject the MSVC cl.exe directory AND the Windows SDK bin directory
# (for mt.exe, rc.exe) into a clean PATH before calling bootstrap.bat. We
# cannot rely on vcvarsall.bat alone: VS 2025's vcvarsall.bat checks
# VSCMD_VER and skips PATH setup when it detects the VC environment was
# already initialised by a parent shell, and even when it runs to completion
# Boost's build.bat links b2.exe via `/MANIFEST:EMBED` which requires
# mt.exe on PATH.
GET_FILENAME_COMPONENT(_cl_dir "${CL_EXE}" DIRECTORY)
STRING(REPLACE "/" "\\" _cl_dir_win "${_cl_dir}")

# Locate the highest-versioned Windows 10/11 SDK x64 bin directory that
# ships mt.exe (needed by link.exe /MANIFEST:EMBED).
SET(_winkits_root "C:/Program Files (x86)/Windows Kits/10/bin")
SET(_sdk_bin_win "")
IF(EXISTS "${_winkits_root}")
  FILE(GLOB _sdk_versions RELATIVE "${_winkits_root}" "${_winkits_root}/10.*")
  IF(_sdk_versions)
    LIST(SORT _sdk_versions)
    LIST(REVERSE _sdk_versions)
    FOREACH(_sdk_ver ${_sdk_versions})
      IF(EXISTS "${_winkits_root}/${_sdk_ver}/x64/mt.exe")
        SET(_sdk_bin "${_winkits_root}/${_sdk_ver}/x64")
        STRING(REPLACE "/" "\\" _sdk_bin_win "${_sdk_bin}")
        MESSAGE(STATUS "boost_bootstrap_vs2025: using Windows SDK bin ${_sdk_bin}")
        BREAK()
      ENDIF()
    ENDFOREACH()
  ENDIF()
ENDIF()
IF(NOT _sdk_bin_win)
  MESSAGE(FATAL_ERROR "boost_bootstrap_vs2025: could not locate a Windows 10/11 SDK x64 bin directory with mt.exe under ${_winkits_root}")
ENDIF()

# Scrub PATH: MSYS2 / Git-bash sometimes plants non-path text in PATH (e.g.
# "'C;...' -> '\\etc\\hosts'") which breaks cmd.exe's SET parser when
# vcvarsall.bat walks the environment.
# Prepend MSVC bin + SDK bin so cl.exe, link.exe, and mt.exe are available.
SET(ENV{PATH} "${_cl_dir_win};${_sdk_bin_win};C:\\Windows\\System32;C:\\Windows;C:\\Windows\\System32\\Wbem")

# Clear vcvarsall.bat "already initialised" sentinels so it actually sets up
# INCLUDE/LIB/PATH for the correct toolset instead of returning early.
SET(ENV{VSCMD_VER} "")
SET(ENV{VSINSTALLDIR} "")
SET(ENV{VCINSTALLDIR} "")
SET(ENV{DevEnvDir} "")
SET(ENV{VCToolsVersion} "")

# Let bat files find sibling scripts via implicit-cwd lookup (Boost's
# build.bat -> config_toolset.bat / guess_toolset.bat).
SET(ENV{NoDefaultCurrentDirectoryInExePath} "")

# Point Boost's VC143 probe at the VS 2025 install. Note: no trailing
# backslash — `set "...\\"` inside bootstrap.bat would be parsed by cmd as an
# escaped quote and break downstream parsing.
SET(ENV{VS170COMNTOOLS} "${VS_COMNTOOLS}")

MESSAGE(STATUS "boost_bootstrap_vs2025: running bootstrap.bat in ${SRC_DIR}")
EXECUTE_PROCESS(
  COMMAND cmd /c bootstrap.bat --with-toolset=${TOOLSET} --with-python=${PYTHON_BIN}
  WORKING_DIRECTORY "${SRC_DIR}"
  RESULT_VARIABLE _rv
)
IF(NOT _rv EQUAL 0)
  MESSAGE(FATAL_ERROR "Boost bootstrap.bat failed with exit code ${_rv}")
ENDIF()

# Overwrite project-config.jam with an explicit <setup> so Boost.Build's
# msvc.jam 14.3 skips auto-detection of vcvarsall.bat (which fails for the
# VS 2025 layout).
STRING(REPLACE "\\" "/" _cl_fwd "${CL_EXE}")
STRING(REPLACE "\\" "/" _vcvarsall_fwd "${VCVARSALL}")

FILE(WRITE "${SRC_DIR}/project-config.jam"
"# Boost.Build Configuration (patched for VS 2025)
# Automatically generated by cmake/dependencies/patch/boost_bootstrap_vs2025.cmake

import option ;

using msvc : 14.3 : \"${_cl_fwd}\" : <setup>\"${_vcvarsall_fwd}\" ;

option.set keep-going : false ;
")

MESSAGE(STATUS "boost_bootstrap_vs2025: wrote patched project-config.jam")
